export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const ROUTE_PATH = 'APP/ROUTE_PATH'
export const AUTH_EMAIL = 'APP/AUTH_EMAIL'

export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS'